[package]
authors = ["Sanemat <o.gata.ken@gmail.com>"]
description = "cli for text to checkstyle."
include = [
    "src/**/*",
    "Cargo.toml",
]
license = "MIT/Apache-2.0"
name = "text2checkstyle_cli"
version = "0.0.6"

[[bin]]
name = "text2checkstyle"
path = "src/main.rs"

[dependencies]
atty = "0.2.3"
clap = "2.26.2"
quick-xml = "0.9.4"
